"""V3 parameterized cycle model (Phase 0 DSE; every number it produces is labelled "model").

Generalizes the V2 output-stationary (OS) cycle model to an R x C array:
R rows = output positions, C columns = output channels, one reduction step k per cycle
(k order (ic*KH + kh)*KW + kw, kw innermost, as in V2 ARCH_SPEC).

V2 basis (constants copied from v2/model/gos_cycle_model.py @ 28dd2ad; the N-generalisation of the
drain from v2/analysis/projection_16x16.py @ 28dd2ad):

    T          = ceil(OC/8) * OH * ceil(OW/8)
    LAYER_CYC  = T*K + C_PIPE            C_PIPE = 29 (RTL-derived, V2 D12)
    TOTAL_CYC  = sum(LAYER_CYC) + C_START(3) + C_DONE(0)

V3 generalization (all PROJECTED, not RTL-derived; each choice is a named parameter of ArrayConfig and
an assumption Pn in ASSUMPTIONS / v3/analysis/DSE_NOTES.md - these are candidate architecture choices,
not facts):

  * tile schedule. A tile issues `issue` cycles; the drain of tile i (D cycles) overlaps the issue of
    tile i+1 and the next tile's accumulators can only be copied to the shadow once the shadow is free,
    so consecutive tiles are spaced by max(issue, D):
        LAYER_CYC = issue_0 + sum_{i>=1} max(issue_i, D) + C_PIPE(D)
    With issue >= D for every tile this is exactly T*K + C_PIPE (the V2 model).
  * drain. V2 copies the accumulators to a shadow register and drains ONE COLUMN per cycle
    (one output channel x 8 pixels, ARCH_SPEC "Drain"); a column holds the R positions of one output
    channel, so D = C cycles and the requant needs R lanes (one channel's qparams per drain cycle).
    C_PIPE(D) = C_PIPE_V2 - (L_DRAIN - 1) + (D - 1)   (as projection_16x16.py, P1 there).
"""
from __future__ import annotations

import math
from dataclasses import dataclass, replace
from typing import Iterable, Sequence

import numpy as np

# ---- V2 RTL-derived latency constants (copied from v2/model/gos_cycle_model.py @ 28dd2ad) -----------
L_LOAD = 1
L_ISSUE = 1
L_MEM_ACC = 2
L_ROT = 1
L_ARRAY = 6
L_DRAIN_V2 = 8      # V2: 8 drain columns per tile
L_QPARAM = 2
L_RQ = 6
L_POOL = 2
L_RETIRE = 1
C_PIPE_V2 = (L_LOAD + L_ISSUE + L_MEM_ACC + L_ROT + L_ARRAY + (L_DRAIN_V2 - 1)
             + L_QPARAM + L_RQ + L_POOL + L_RETIRE)          # = 29
C_START_V2 = 3
C_DONE_V2 = 0

CLOCKS_MHZ = (249.9975, 333.33)    # V3 D2: PLL-reachable PL clocks

MODES_OS_ONLY = ("os",)
MODES_BEST = ("os", "splitk", "dw")

ASSUMPTIONS = {
    "P1": "OS tiling: R rows = output positions, C cols = output channels, one k per cycle; V2 latencies "
          "(L_*) kept at their 8x8 RTL values, only the drain length scales (projected); "
          "extra_pipe_stages adds 1 cycle per layer each.",
    "P2": "Drain: shadow copy + one column (1 OC x R positions) per cycle -> D = C cycles "
          "(drain_axis='col', V2); tiles are spaced by max(issue, D) so short-K tiles stall.",
    "P3": "Row mapping 'x': R consecutive ox of one output row (ACT bank = x mod R + rotator, V2); "
          "'xy': R consecutive flattened positions (ACT bank = flat index mod R + rotator, conflict-free "
          "only when IW == OW*stride, i.e. SAME padding; VALID layers fall back to 'x').",
    "P4": "SAME padding: zeros generated by the read path (masked bank read), 0 cycles; "
          "pad_penalty_per_tile cycles added per tile of a padded layer (default 0).",
    "P5": "Stride s>1 with banked ACT: 'half_rate' = s cycles per k-step (bank conflicts), "
          "'phase_split' = producer writes an x-(and y-, for 'xy') phase de-interleaved layout, 0 penalty, "
          "costs a layout flag; 'dual_port' = 2 reads per bank per cycle -> ceil(s/2).",
    "P6": "Residual add 'fused': skip tensor read in the drain/requant path, R bytes per drain cycle; "
          "if skip_read_bytes_per_cycle < R the drain slows; option-A stride-2 skip reads follow P5. "
          "'separate': extra element-wise pass ceil(OC*OH*OW/eltwise_lanes) + eltwise_pipe cycles.",
    "P7": "GAP 'fused': accumulated in the last conv's drain, gap_fused_cycles extra (default 0); "
          "'separate': ceil(OC*OH*OW/gap_lanes) + gap_pipe cycles.",
    "P8": "Split-K (B1): S | R rows take k-slices (k interleaved over the S slices), R/S positions per "
          "tile, issue = ceil(K/S); partial sums reduced on the drain path by a log2(S)-deep adder tree "
          "(+log2(S) cycles per layer); needs S*C distinct weight bytes per cycle and an ic-interleaved "
          "input layout written by the producer; with packing S <= R/2 (packed pairs share a weight).",
    "P9": "Depthwise (B2): 'dw' mode = columns are independent channels, issue = KH*KW per tile, needs "
          "R*C distinct activation bytes per cycle; dw layers in 'os' mode use 1 of C columns.",
    "P10": "Mode selection (B3): per layer the min-cycle mode among the enabled, applicable modes.",
    "P11": "Packing: 2 MACs per DSP48E2 = two row positions sharing the column weight; same cycles, PE "
           "DSPs = ceil(R/2)*C; every pack_kmax issued k-steps the packed fields are extracted at "
           "pack_extract_cycles stall cycles each (kmax, cost = PLACEHOLDERS until WS5 measures them).",
    "P12": "C1 weight sparsity: block = C consecutive OCs x 1 k-step; an OC tile issues only its nonzero "
           "k-steps (static schedule); 'density' shortcut: ceil(d*K) per OC tile; applies to os/splitk, "
           "not dw. Utilisation stays macs_dense/(R*C*cycles) and can exceed 1.",
    "P13": "C2 activation skipping: a k-step of a tile is skipped when all R broadcast activations are zero "
           "(padding and masked tail rows count as zero); data-dependent, measured per image.",
    "P14": "WS (B4) sketch, first principles only: R x C weights stationary (R k-steps x C OCs), one output "
           "position per cycle, weight reload R cycles double-buffered, skew R+C-1 once per layer, partial "
           "sums accumulated across ceil(K/R) blocks in an output buffer; not derived from any RTL.",
    "P15": "Requant: lanes = values per drain cycle (R for drain_axis='col'), requant_dsp_per_lane DSPs each "
           "(V2: 2); C_START = 3, C_DONE = 0 (V2 RTL values).",
}


def ceil_div(a: int, b: int) -> int:
    return -(-a // b)


def log2_ceil(n: int) -> int:
    return 0 if n <= 1 else (n - 1).bit_length()


@dataclass(frozen=True)
class ArrayConfig:
    """One candidate architecture. Every field is a modelling choice (see ASSUMPTIONS), not a fact."""

    R: int = 8
    """Array rows = output positions per tile (P1)."""
    C: int = 8
    """Array columns = output channels per tile (P1)."""
    row_map: str = "x"
    """'x' or 'xy' (P3)."""
    stride2: str = "phase_split"
    """Stride>1 strategy: 'half_rate' | 'phase_split' | 'dual_port' (P5)."""
    modes: tuple = MODES_OS_ONLY
    """Enabled dataflow modes, subset of ('os','splitk','dw','ws') (P10)."""
    residual: str = "fused"
    """'fused' | 'separate' (P6)."""
    gap: str = "fused"
    """'fused' | 'separate' (P7)."""
    packed: bool = False
    """INT8 DSP packing, 2 MACs per DSP sharing the weight (P11)."""
    pack_kmax: int | None = None
    """Max issued k-steps before the packed fields must be extracted; None = unlimited (PLACEHOLDER)."""
    pack_extract_cycles: int = 1
    """Stall cycles per extraction (PLACEHOLDER, P11)."""
    pad_penalty_per_tile: int = 0
    """Extra cycles per tile of a SAME-padded layer (P4)."""
    drain_axis: str = "col"
    """'col' (V2: one OC column per cycle, D = C) or 'row' (one position per cycle, D = R) (P2)."""
    drain_units_per_cycle: int = 1
    """Columns (or rows) drained per cycle (V2: 1)."""
    skip_read_bytes_per_cycle: int | None = None
    """Fused-residual skip read bandwidth; None = one value per requant lane (no drain slowdown) (P6)."""
    eltwise_lanes: int | None = None
    """Separate residual pass lanes; None = R (P6)."""
    eltwise_pipe: int | None = None
    """Separate residual pass fill/flush cycles; None = C_PIPE(D) (placeholder) (P6)."""
    gap_fused_cycles: int = 0
    """Extra cycles of a fused GAP (P7)."""
    gap_lanes: int | None = None
    """Separate GAP pass lanes; None = R (P7)."""
    gap_pipe: int | None = None
    """Separate GAP pass fill/flush; None = C_PIPE(D) (placeholder) (P7)."""
    splitk_s: tuple | None = None
    """Split-K factors tried; None = every power of two 2..R dividing R (P8)."""
    wgt_bytes_per_cycle: int | None = None
    """Weight read bandwidth; None = whatever the mode needs (C for os/dw, S*C for split-K)."""
    dw_act_bytes_per_cycle: int | None = None
    """Activation read bandwidth in dw mode; None = R*C (whatever it needs) (P9)."""
    extra_pipe_stages: int = 0
    """Extra pipeline stages per layer vs V2 (e.g. deeper broadcast trees) (P1)."""
    c_start: int = C_START_V2
    c_done: int = C_DONE_V2
    requant_lanes: int | None = None
    """None = derived from the drain axis (R for 'col') (P15)."""
    requant_dsp_per_lane: int = 2
    """V2 requant: 2 DSP48E2 per lane (V2 impl: 80 DSP = 64 PE + 8 lanes x 2)."""

    def __post_init__(self):
        assert self.R >= 1 and self.C >= 1
        assert self.row_map in ("x", "xy"), self.row_map
        assert self.stride2 in ("half_rate", "phase_split", "dual_port"), self.stride2
        assert set(self.modes) <= {"os", "splitk", "dw", "ws"} and "os" in self.modes, self.modes
        assert self.residual in ("fused", "separate") and self.gap in ("fused", "separate")
        assert self.drain_axis in ("col", "row")
        assert not self.packed or self.R % 2 == 0, "packing pairs rows: R must be even"
        assert self.pack_kmax is None or self.pack_kmax >= 1

    # ---- derived quantities
    @property
    def drain_len(self) -> int:
        units = self.C if self.drain_axis == "col" else self.R
        return ceil_div(units, self.drain_units_per_cycle)

    @property
    def lanes(self) -> int:
        """Values leaving the drain per cycle = requant lanes."""
        if self.requant_lanes is not None:
            return self.requant_lanes
        return (self.R if self.drain_axis == "col" else self.C) * self.drain_units_per_cycle

    @property
    def pe_dsps(self) -> int:
        return (ceil_div(self.R, 2) if self.packed else self.R) * self.C

    @property
    def requant_dsps(self) -> int:
        return self.lanes * self.requant_dsp_per_lane

    def c_pipe(self, drain: int | None = None) -> int:
        d = self.drain_len if drain is None else drain
        return C_PIPE_V2 - (L_DRAIN_V2 - 1) + (d - 1) + self.extra_pipe_stages

    def label(self) -> str:
        pk = "nopack" if not self.packed else f"pack(kmax={self.pack_kmax})"
        return (f"{self.R}x{self.C}/{self.row_map}/{'+'.join(self.modes)}/{self.stride2}/{pk}/"
                f"res={self.residual}/gap={self.gap}")


# ---------------------------------------------------------------- schedule primitive
def schedule(issues: Sequence[tuple[int, int]], drain: int, c_pipe: int) -> dict:
    """Layer cycles for tiles given as (issue_cycles, count) groups in issue order.

    LAYER_CYC = issue_0 + sum_{i>=1} max(issue_i, drain) + c_pipe   (P2).
    """
    groups = [(int(i), int(n)) for i, n in issues if n > 0]
    if not groups:
        return {"tiles": 0, "issue": 0, "stall": 0, "cycles": 0}
    tiles = sum(n for _, n in groups)
    issue = sum(i * n for i, n in groups)
    spaced = sum(max(i, drain) * n for i, n in groups)
    first = groups[0][0]
    spaced += first - max(first, drain)          # the first tile is not spaced after a predecessor
    return {"tiles": tiles, "issue": issue, "stall": spaced - issue, "cycles": spaced + c_pipe}


def _pack_extra(issue: int, cfg: ArrayConfig) -> int:
    if not cfg.packed or cfg.pack_kmax is None or issue <= 0:
        return 0
    return (ceil_div(issue, cfg.pack_kmax) - 1) * cfg.pack_extract_cycles


def _stride_factor(layer: dict, cfg: ArrayConfig, positions_per_tile: int) -> int:
    s = int(layer.get("stride", 1))
    if s <= 1 or positions_per_tile <= 1:
        return 1
    if cfg.stride2 == "half_rate":
        return s
    if cfg.stride2 == "dual_port":
        return ceil_div(s, 2)
    return 1                                     # phase_split


def _is_same(layer: dict) -> bool:
    """IW == OW*stride and IH == OH*stride (SAME padding): flattened reads stay contiguous (P3)."""
    s = int(layer.get("stride", 1))
    ih = layer.get("ih", layer["oh"])
    iw = layer.get("iw", layer["ow"])
    return ih == layer["oh"] * s and iw == layer["ow"] * s


def pos_tiles(layer: dict, rows: int, row_map: str) -> tuple[int, str]:
    """Number of position tiles for `rows` positions per tile; returns (tiles, mapping actually used)."""
    oh, ow = layer["oh"], layer["ow"]
    if row_map == "xy" and (oh * ow == 1 or _is_same(layer) or oh == 1):
        return ceil_div(oh * ow, rows), "xy"
    return oh * ceil_div(ow, rows), "x"


def _pad_pen(layer: dict, cfg: ArrayConfig) -> int:
    return cfg.pad_penalty_per_tile if int(layer.get("pad", 0)) > 0 else 0


def _residual_drain(layer: dict, cfg: ArrayConfig, drain: int) -> int:
    """Drain length with a fused residual add whose skip read may be slower than the drain (P6)."""
    if not layer.get("residual_from") or cfg.residual != "fused":
        return drain
    bw = cfg.skip_read_bytes_per_cycle if cfg.skip_read_bytes_per_cycle is not None else cfg.lanes
    per_unit = ceil_div(cfg.lanes, bw)
    if layer.get("skip_kind") == "A" and cfg.stride2 == "half_rate":
        per_unit *= 2   # option-A skip = stride-2 subsample of the block input, read from a non-split layout
    return drain * per_unit


def _k_eff(layer: dict) -> int:
    return int(layer["k"])


def _nnz_list(layer: dict, n_oc_tiles: int, density: float, nnz: Sequence[int] | None, K: int) -> list[int]:
    if nnz is not None:
        assert len(nnz) == n_oc_tiles, (len(nnz), n_oc_tiles)
        return [int(x) for x in nnz]
    if density >= 1.0:
        return [K] * n_oc_tiles
    return [max(0, math.ceil(density * K))] * n_oc_tiles


def _result(mode, layer, cfg, sched, T, drain, cpipe, extra=None) -> dict:
    macs = int(layer["macs"])
    r = {"mode": mode, "T": T, "drain": drain, "c_pipe": cpipe, "issue": sched["issue"],
         "stall": sched["stall"], "cycles": sched["cycles"], "macs": macs,
         "util": macs / (cfg.R * cfg.C * sched["cycles"]) if sched["cycles"] else 0.0}
    r.update(extra or {})
    return r


# ---------------------------------------------------------------- modes
def os_layer(layer: dict, cfg: ArrayConfig, density: float = 1.0, nnz: Sequence[int] | None = None) -> dict:
    """Output-stationary mode (V2 dataflow, P1-P7, P11, P12). Depthwise layers use 1 column per tile."""
    pt, used = pos_tiles(layer, cfg.R, cfg.row_map)
    sf = _stride_factor(layer, cfg, cfg.R)
    drain = _residual_drain(layer, cfg, cfg.drain_len)
    cpipe = cfg.c_pipe(drain)
    if layer["kind"] == "dw":
        kk = int(layer["kh"]) * int(layer["kw"])
        n_oc = int(layer["oc"])                  # one channel per tile (P9)
        issue = kk * sf + _pad_pen(layer, cfg)
        issue += _pack_extra(issue, cfg)
        sched = schedule([(issue, n_oc * pt)], drain, cpipe)
        return _result("os", layer, cfg, sched, n_oc * pt, drain, cpipe,
                       {"row_map_used": used, "pos_tiles": pt, "oc_tiles": n_oc, "split_s": 1})
    K = _k_eff(layer)
    n_oc = ceil_div(int(layer["oc"]), cfg.C)
    wrate = 1 if cfg.wgt_bytes_per_cycle is None else ceil_div(cfg.C, cfg.wgt_bytes_per_cycle)
    groups = []
    for kz in _nnz_list(layer, n_oc, density, nnz, K):
        issue = kz * sf * wrate + _pad_pen(layer, cfg)
        issue += _pack_extra(issue, cfg)
        groups.append((issue, pt))
    sched = schedule(groups, drain, cpipe)
    return _result("os", layer, cfg, sched, n_oc * pt, drain, cpipe,
                   {"row_map_used": used, "pos_tiles": pt, "oc_tiles": n_oc, "split_s": 1})


def splitk_factors(cfg: ArrayConfig) -> list[int]:
    if cfg.splitk_s is not None:
        cand = list(cfg.splitk_s)
    else:
        cand = [1 << i for i in range(1, cfg.R.bit_length()) if (1 << i) <= cfg.R]
    out = [s for s in cand if s >= 2 and cfg.R % s == 0]
    if cfg.packed:
        out = [s for s in out if s <= cfg.R // 2]      # P8/P11: packed pairs must share a weight
    return out


def splitk_layer(layer: dict, cfg: ArrayConfig, S: int, density: float = 1.0,
                 nnz: Sequence[int] | None = None) -> dict | None:
    """Split-K mode (B1, P8) with factor S: R/S positions per tile, S k-slices. None if not applicable."""
    if layer["kind"] == "dw" or int(layer.get("groups", 1)) != 1 or cfg.R % S or S < 2:
        return None
    rows = cfg.R // S
    pt, used = pos_tiles(layer, rows, cfg.row_map)
    sf = _stride_factor(layer, cfg, rows)
    drain = _residual_drain(layer, cfg, cfg.drain_len)
    tree = log2_ceil(S)
    cpipe = cfg.c_pipe(drain) + tree
    K = _k_eff(layer)
    n_oc = ceil_div(int(layer["oc"]), cfg.C)
    need = S * cfg.C
    wrate = 1 if cfg.wgt_bytes_per_cycle is None else ceil_div(need, cfg.wgt_bytes_per_cycle)
    groups = []
    for kz in _nnz_list(layer, n_oc, density, nnz, K):
        issue = ceil_div(kz, S) * sf * wrate + _pad_pen(layer, cfg)
        issue += _pack_extra(issue, cfg)
        groups.append((issue, pt))
    sched = schedule(groups, drain, cpipe)
    return _result("splitk", layer, cfg, sched, n_oc * pt, drain, cpipe,
                   {"row_map_used": used, "pos_tiles": pt, "oc_tiles": n_oc, "split_s": S,
                    "wgt_bytes_per_cycle_needed": need, "reduction_depth": tree})


def dw_layer(layer: dict, cfg: ArrayConfig) -> dict | None:
    """Depthwise mode (B2, P9): columns = independent channels, issue = KH*KW per tile."""
    if layer["kind"] != "dw":
        return None
    pt, used = pos_tiles(layer, cfg.R, cfg.row_map)
    sf = _stride_factor(layer, cfg, cfg.R)
    drain = _residual_drain(layer, cfg, cfg.drain_len)
    cpipe = cfg.c_pipe(drain)
    kk = int(layer["kh"]) * int(layer["kw"])
    need = cfg.R * cfg.C
    arate = 1 if cfg.dw_act_bytes_per_cycle is None else ceil_div(need, cfg.dw_act_bytes_per_cycle)
    n_oc = ceil_div(int(layer["oc"]), cfg.C)
    issue = kk * sf * arate + _pad_pen(layer, cfg)
    issue += _pack_extra(issue, cfg)
    sched = schedule([(issue, n_oc * pt)], drain, cpipe)
    return _result("dw", layer, cfg, sched, n_oc * pt, drain, cpipe,
                   {"row_map_used": used, "pos_tiles": pt, "oc_tiles": n_oc, "split_s": 1,
                    "act_bytes_per_cycle_needed": need})


def ws_layer(layer: dict, cfg: ArrayConfig) -> dict | None:
    """Weight-stationary SKETCH (B4, P14), first principles only, no packing, not for dw layers.

    blocks = ceil(K/R) * ceil(OC/C); each block streams P = OH*OW positions (one per cycle, stride
    factor P5) and needs an R-cycle weight reload (double-buffered: block time = max(P*sf, R));
    + R + C - 1 skew cycles and the V2 non-drain pipeline once per layer.
    """
    if layer["kind"] == "dw" or int(layer.get("groups", 1)) != 1:
        return None
    K = _k_eff(layer)
    P = int(layer["oh"]) * int(layer["ow"])
    sf = _stride_factor(layer, cfg, 2)
    blocks = ceil_div(K, cfg.R) * ceil_div(int(layer["oc"]), cfg.C)
    per = max(P * sf, cfg.R)
    cpipe = cfg.c_pipe(1) + cfg.R + cfg.C - 1
    sched = {"issue": blocks * P * sf, "stall": blocks * (per - P * sf), "cycles": blocks * per + cpipe}
    return _result("ws", layer, cfg, sched, blocks, 1, cpipe,
                   {"row_map_used": "", "pos_tiles": P, "oc_tiles": ceil_div(int(layer["oc"]), cfg.C),
                    "split_s": 1})


def layer_candidates(layer: dict, cfg: ArrayConfig, density: float = 1.0,
                     nnz: Sequence[int] | None = None) -> list[dict]:
    """Every applicable (mode, factor) result for one layer under cfg.modes."""
    d = density if layer["kind"] != "dw" else 1.0
    out = [os_layer(layer, cfg, d, nnz)]
    if "splitk" in cfg.modes:
        for S in splitk_factors(cfg):
            r = splitk_layer(layer, cfg, S, d, nnz)
            if r is not None:
                out.append(r)
    if "dw" in cfg.modes:
        r = dw_layer(layer, cfg)
        if r is not None:
            out.append(r)
    if "ws" in cfg.modes:
        r = ws_layer(layer, cfg)
        if r is not None:
            out.append(r)
    return out


def layer_cycles(layer: dict, cfg: ArrayConfig, density: float = 1.0, nnz: Sequence[int] | None = None) -> dict:
    """Min-cycle candidate (B3, P10); ties keep the earlier mode (os first). Adds os_cycles for reference."""
    cands = layer_candidates(layer, cfg, density, nnz)
    best = min(cands, key=lambda r: r["cycles"])
    best = dict(best)
    best["os_cycles"] = cands[0]["cycles"]
    best["drain_hidden"] = best["stall"] == 0
    return best


# ---------------------------------------------------------------- extra passes
def residual_pass_cycles(layer: dict, cfg: ArrayConfig) -> int:
    if not layer.get("residual_from") or cfg.residual != "separate":
        return 0
    lanes = cfg.eltwise_lanes or cfg.R
    pipe = cfg.eltwise_pipe if cfg.eltwise_pipe is not None else cfg.c_pipe()
    return ceil_div(int(layer["oc"]) * int(layer["oh"]) * int(layer["ow"]), lanes) + pipe


def gap_pass_cycles(layer: dict, cfg: ArrayConfig) -> int:
    if not layer.get("gap"):
        return 0
    if cfg.gap == "fused":
        return cfg.gap_fused_cycles
    lanes = cfg.gap_lanes or cfg.R
    pipe = cfg.gap_pipe if cfg.gap_pipe is not None else cfg.c_pipe()
    return ceil_div(int(layer["oc"]) * int(layer["oh"]) * int(layer["ow"]), lanes) + pipe


def net_cycles(layers: Iterable[dict], cfg: ArrayConfig, density: float | dict = 1.0,
               masks: dict | None = None) -> dict:
    """Per-layer results + total. density: float (all conv/fc layers) or {layer: d}; masks: {layer: nnz list}.

    TOTAL = sum(layer cycles) + residual/GAP passes + C_START + C_DONE.
    """
    rows, total, macs, extra = [], 0, 0, 0
    for L in layers:
        d = density.get(L["layer"], 1.0) if isinstance(density, dict) else density
        nnz = masks.get(L["layer"]) if masks else None
        r = layer_cycles(L, cfg, d, nnz)
        r["layer"] = L["layer"]
        r["residual_pass"] = residual_pass_cycles(L, cfg)
        r["gap_pass"] = gap_pass_cycles(L, cfg)
        rows.append(r)
        total += r["cycles"] + r["residual_pass"] + r["gap_pass"]
        extra += r["residual_pass"] + r["gap_pass"]
        macs += int(L["macs"])
    total += cfg.c_start + cfg.c_done
    return {"layers": rows, "cycles": total, "macs": macs, "extra_pass_cycles": extra,
            "util": macs / (cfg.R * cfg.C * total),
            "latency_us": {f: total / f for f in CLOCKS_MHZ}}


# ---------------------------------------------------------------- C1: masks
def block_mask(w: np.ndarray, C: int) -> np.ndarray:
    """w: (OC, K) weights in k order (ic*KH+kh)*KW+kw -> (ceil(OC/C), K) bool, True = block has a nonzero."""
    w = np.asarray(w)
    oc, K = w.shape
    pad = ceil_div(oc, C) * C - oc
    wp = np.pad(w != 0, ((0, pad), (0, 0)))
    return wp.reshape(-1, C, K).any(axis=1)


def nnz_from_mask(mask: np.ndarray) -> list[int]:
    return [int(x) for x in np.asarray(mask).sum(axis=1)]


# ---------------------------------------------------------------- C2: activation zeros
def _im2col_zero(act: np.ndarray, layer: dict) -> np.ndarray:
    """(P, K) bool: activation feeding position p at k-step k is zero (padding counts as zero)."""
    act = np.asarray(act)
    ic, ih, iw = act.shape
    kh, kw, s, p = int(layer["kh"]), int(layer["kw"]), int(layer.get("stride", 1)), int(layer.get("pad", 0))
    oh, ow = int(layer["oh"]), int(layer["ow"])
    z = np.pad(act == 0, ((0, 0), (p, p), (p, p)), constant_values=True)
    cols = np.empty((oh, ow, ic, kh, kw), dtype=bool)
    for y in range(kh):
        for x in range(kw):
            cols[:, :, :, y, x] = z[:, y:y + s * oh:s, x:x + s * ow:s].transpose(1, 2, 0)
    return cols.reshape(oh * ow, ic * kh * kw)


def _tile_ids(layer: dict, R: int, row_map: str) -> np.ndarray:
    oh, ow = int(layer["oh"]), int(layer["ow"])
    pt, used = pos_tiles(layer, R, row_map)
    flat = np.arange(oh * ow)
    if used == "xy":
        return flat // R
    return (flat // ow) * ceil_div(ow, R) + (flat % ow) // R


def zero_ksteps(act: np.ndarray, layer: dict, R: int, row_map: str = "x") -> np.ndarray:
    """C2 (P13), os mode, groups=1 layers: per position tile, the number of k-steps whose R broadcast
    activations are all zero. act = layer INPUT, int8 (IC, IH, IW). Masked tail rows are ignored."""
    assert layer["kind"] != "dw", "C2 for dw layers is not modelled"
    z = _im2col_zero(act, layer)
    tid = _tile_ids(layer, R, row_map)
    starts = np.flatnonzero(np.r_[True, tid[1:] != tid[:-1]])
    allz = np.logical_and.reduceat(z, starts, axis=0)          # (pos_tiles, K)
    return allz.sum(axis=1)


def layer_cycles_c2(layer: dict, cfg: ArrayConfig, act: np.ndarray) -> dict:
    """OS-mode layer cycles for one image with all-zero broadcast k-steps skipped (C2). Dense weights."""
    zk = zero_ksteps(act, layer, cfg.R, cfg.row_map)
    K = _k_eff(layer)
    sf = _stride_factor(layer, cfg, cfg.R)
    drain = _residual_drain(layer, cfg, cfg.drain_len)
    cpipe = cfg.c_pipe(drain)
    n_oc = ceil_div(int(layer["oc"]), cfg.C)
    groups = []
    for _ in range(n_oc):
        for z in zk:
            issue = (K - int(z)) * sf + _pad_pen(layer, cfg)
            groups.append((issue + _pack_extra(issue, cfg), 1))
    sched = schedule(groups, drain, cpipe)
    dense = os_layer(layer, cfg)
    return {"cycles": sched["cycles"], "dense_cycles": dense["cycles"],
            "saved_cycles": dense["cycles"] - sched["cycles"],
            "skipped_ksteps": int(zk.sum()) * n_oc, "stall": sched["stall"]}


def with_(cfg: ArrayConfig, **kw) -> ArrayConfig:
    return replace(cfg, **kw)
