"""Figure generators (PDF, IEEEtran column widths, 8-pt text, grayscale + hatching)."""
from __future__ import annotations

import csv
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.patches import Patch, Rectangle  # noqa: E402
from matplotlib.transforms import blended_transform_factory  # noqa: E402

from paperdata import INA_LABEL, a3_net, at, div, impl_variants, latest, power_summaries  # noqa: E402
from paperlib import DRYRUN_MARK, NETS, Artifact, Store, _rel, fnum  # noqa: E402

COL_W, DCOL_W = 3.5, 7.16           # IEEEtran single / double column (in)
FS = 8
# grayscale encodings (fill, edge, hatch) -- distinguishable in print without colour
ST_MODEL = dict(facecolor="white", edgecolor="black", hatch="")
ST_RTL = dict(facecolor="0.55", edgecolor="black", hatch="")
ST_HW = dict(facecolor="black", edgecolor="black", hatch="")
ST_PH = dict(facecolor="none", edgecolor="0.55", hatch="////", linestyle=(0, (2, 1.5)))
NET_TITLE = {"lenet5": "LeNet-5", "cifar10": "CIFAR-10"}


def style():
    plt.rcParams.update({
        "font.family": "serif", "font.serif": ["STIXGeneral", "DejaVu Serif"], "mathtext.fontset": "stix",
        "font.size": FS, "axes.labelsize": FS, "axes.titlesize": FS, "xtick.labelsize": FS - 1,
        "ytick.labelsize": FS - 1, "legend.fontsize": FS - 1, "axes.linewidth": 0.6,
        "xtick.major.width": 0.5, "ytick.major.width": 0.5, "xtick.major.size": 2.5, "ytick.major.size": 2.5,
        "ytick.minor.size": 1.5, "ytick.minor.width": 0.4, "hatch.linewidth": 0.5, "hatch.color": "0.55",
        "pdf.fonttype": 42, "ps.fonttype": 42, "axes.spines.top": False, "axes.spines.right": False,
        "legend.frameon": False, "savefig.dpi": 600,
    })


class FCtx:
    def __init__(self, store: Store, out: Path, dryrun: bool):
        self.store, self.out, self.dryrun = store, out, dryrun

    def art(self, name):
        return Artifact(self.store, name, "figure")

    @property
    def hw_name(self):
        return "KV260 (DRY RUN)" if self.dryrun else "KV260 (measured)"

    def save(self, art: Artifact, fig, data_rows: list[dict]):
        if self.dryrun:
            fig.text(0.5, 0.5, DRYRUN_MARK, ha="center", va="center", rotation=25, fontsize=22,
                     color="0.3", alpha=0.35, weight="bold", zorder=100)
        p = self.out / f"{art.name}.pdf"
        p.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(p,
                    metadata={"CreationDate": None, "ModDate": None,
                              "Subject": "generated by v2/paper/scripts/make_all.py; see MANIFEST.json"})
        plt.close(fig)
        art.outputs.append(_rel(p))
        if data_rows:                                   # the plotted numbers, for review
            q = self.out / f"{art.name}.data.csv"
            with open(q, "w", newline="") as f:
                w = csv.DictWriter(f, fieldnames=list(dict.fromkeys(k for r in data_rows for k in r)))
                w.writeheader()
                w.writerows(data_rows)
            art.outputs.append(_rel(q))
        return art


def _placeholder_box(ax, x0, width, trans_y=True):
    """Hatched outline spanning the whole axis height at x0..x0+width: never a data value."""
    tr = blended_transform_factory(ax.transData, ax.transAxes)
    ax.add_patch(Rectangle((x0, 0.0), width, 1.0, transform=tr, fill=False, lw=0.5, zorder=1, **{
        k: v for k, v in ST_PH.items() if k != "facecolor"}))


def _pending_label(ax, text="board data pending"):
    ax.text(0.99, 0.97, text, transform=ax.transAxes, ha="right", va="top", fontsize=FS - 1, style="italic",
            color="0.2", bbox=dict(boxstyle="round,pad=0.2", fc="white", ec="0.55", lw=0.5, ls="--"), zorder=50)


# --------------------------------------------------------------------------------------------
# A3: three-way per-layer cycle agreement (priority figure)
# --------------------------------------------------------------------------------------------
def _a3_panel(ax, art: Artifact, net: str, d: list[dict], hw_name: str, show_ylabel=True, ann_fs=FS - 1,
              row_labels=True):
    n = len(d)
    w = 0.26
    xs = list(range(n))
    has_hw = any(x["hw"] is not None for x in d)
    for i, x in enumerate(d):
        xi = i + (0.35 if x["is_total"] else 0.0)
        xs[i] = xi
        ax.bar(xi - w, x["model"].value, w, lw=0.5, zorder=3, **ST_MODEL)
        if x["rtl"] is not None:
            ax.bar(xi, x["rtl"].value, w, lw=0.5, zorder=3, **ST_RTL)
        if x["hw"] is not None:
            ax.bar(xi + w, x["hw"].value, w, lw=0.5, zorder=3, **ST_HW)
        else:
            art.placeholder(f"A3 {net} {x['layer']}: hw_a2_a3_cycles.csv (source=hw)")
            _placeholder_box(ax, xi + w / 2, w)
    ax.set_yscale("log")
    lo = min(x["model"].value for x in d)
    hi = max(max(x["model"].value, (x["rtl"] or x["model"]).value, (x["hw"] or x["model"]).value) for x in d)
    ax.set_ylim(lo / 2.2, hi * 2.2)
    ax.set_xlim(-0.6, xs[-1] + 0.6)
    ax.set_xticks(xs)
    ax.set_xticklabels([("total" if x["is_total"] else art.label(x["layer"], "cycle_model.csv:layer")) for x in d])
    if d[-1]["is_total"]:
        ax.axvline((xs[-2] + xs[-1]) / 2, color="0.6", lw=0.5, ls=":", zorder=0)
    ax.yaxis.grid(True, which="major", color="0.88", lw=0.4, zorder=0)
    if show_ylabel:
        ax.set_ylabel("cycles (log)")
    # per-layer error annotations (computed from the CSV values), two rows above the plot area
    tr = blended_transform_factory(ax.transData, ax.transAxes)
    for xi, x in zip(xs, d):
        r = x["rtl_err"].fmt(art, "pct2") if x["rtl_err"] is not None else "n/a"
        ax.text(xi, 1.13, r.replace("$-$", "−") + "%", transform=tr, ha="center", va="bottom",
                fontsize=ann_fs, color="0.15")
        h = (x["hw_err"].fmt(art, "pct2").replace("$-$", "−") + "%") if x["hw_err"] is not None else "TBD"
        ax.text(xi, 1.02, h, transform=tr, ha="center", va="bottom", fontsize=ann_fs,
                color="0.15" if x["hw_err"] is not None else "0.45",
                style="normal" if x["hw_err"] is not None else "italic")
    if row_labels:
        ax.text(-0.01, 1.13, "RTL vs model:", transform=ax.transAxes, ha="right", va="bottom", fontsize=ann_fs)
        ax.text(-0.01, 1.02, "KV260 vs model:", transform=ax.transAxes, ha="right", va="bottom",
                fontsize=ann_fs)
    ax.set_title(NET_TITLE.get(net, net), loc="center", pad=27, fontsize=FS, weight="bold")
    return has_hw


def _a3_legend(fig, hw_name, has_hw, **kw):
    handles = [Patch(lw=0.5, label="model (analytical)", **ST_MODEL),
               Patch(lw=0.5, label="RTL sim (xsim)", **ST_RTL),
               Patch(lw=0.5, label=hw_name, **ST_HW) if has_hw else
               Patch(lw=0.5, label="KV260: board data pending", fill=False,
                     **{k: v for k, v in ST_PH.items() if k != "facecolor"})]
    fig.legend(handles=handles, ncol=3, handlelength=1.4, columnspacing=1.0, handletextpad=0.4, **kw)


def fig_a3(c: FCtx, wide: bool) -> Artifact:
    art = c.art("fig_a3_cycles_wide" if wide else "fig_a3_cycles")
    data = {net: a3_net(art, net) for net in NETS}
    nets = [n for n in NETS if data[n]]
    if wide:
        fig, axs = plt.subplots(1, len(nets), figsize=(DCOL_W, 2.45), layout="constrained",
                                gridspec_kw=dict(width_ratios=[len(data[n]) for n in nets]))
    else:
        fig, axs = plt.subplots(len(nets), 1, figsize=(COL_W, 4.0), layout="constrained")
        fig.get_layout_engine().set(hspace=0.06)
    axs = list(axs) if len(nets) > 1 else [axs]
    has_hw = False
    for i, (ax, net) in enumerate(zip(axs, nets)):
        has_hw |= _a3_panel(ax, art, net, data[net], c.hw_name, show_ylabel=(i == 0 or not wide),
                            row_labels=(i == 0 or not wide))
    if wide:
        _a3_legend(fig, c.hw_name, has_hw, loc="outside lower center")
    else:
        _a3_legend(fig, c.hw_name, has_hw, loc="outside lower center")
    rows = []
    for net in nets:
        for x in data[net]:
            rows.append({"net": net, "layer": x["layer"], "model_cycles": x["model"].value,
                         "rtl_cycles": x["rtl"].value if x["rtl"] else "",
                         "hw_cycles": x["hw"].value if x["hw"] else "",
                         "rtl_err_pct": x["rtl_err"].value if x["rtl_err"] else "",
                         "hw_err_pct": x["hw_err"].value if x["hw_err"] else "",
                         "model_src": x["model"].origin, "rtl_src": x["rtl"].origin if x["rtl"] else "",
                         "hw_src": x["hw"].origin if x["hw"] else "board data pending"})
    return c.save(art, fig, rows)


# --------------------------------------------------------------------------------------------
# A4: MAC_ACTIVE / cycles and theoretical PE utilization per layer
# --------------------------------------------------------------------------------------------
def fig_a4(c: FCtx) -> Artifact:
    art = c.art("fig_a4_util")
    data = {net: a3_net(art, net) for net in NETS}
    nets = [n for n in NETS if data[n]]
    fig, axs = plt.subplots(1, len(nets), figsize=(COL_W, 2.3), sharey=True, layout="constrained",
                            gridspec_kw=dict(width_ratios=[len(data[n]) for n in nets]))
    axs = list(axs) if len(nets) > 1 else [axs]
    rows, any_hw = [], False
    w = 0.26
    for ax, net in zip(axs, nets):
        hw = latest(art.rows("hw_a4_util.csv", hw=True, net=net) or [], lambda r: r["layer"])
        for i, x in enumerate(data[net]):
            am = div(x["mac_model"], x["model"], "MAC_ACTIVE/cycles").value * 100
            ut = x["util_th"].value * 100
            h = hw.get(x["layer"])
            ax.bar(i - w, am, w, lw=0.5, zorder=3, **ST_MODEL)
            ax.bar(i, ut, w, lw=0.5, zorder=3, facecolor="0.8", edgecolor="black", hatch="\\\\\\\\")
            if h and h.get("active_frac"):
                any_hw = True
                ax.bar(i + w, fnum(h["active_frac"]) * 100, w, lw=0.5, zorder=3, **ST_HW)
            else:
                art.placeholder(f"A4 {net} {x['layer']}: hw_a4_util.csv")
                _placeholder_box(ax, i + w / 2, w)
            rows.append({"net": net, "layer": x["layer"], "mac_active_over_cycles_pct_model": am,
                         "pe_util_theoretical_pct": ut,
                         "hw_active_frac_pct": fnum(h["active_frac"]) * 100 if h and h.get("active_frac") else "",
                         "src": f"{x['mac_model'].origin}; {x['model'].origin}; {x['util_th'].origin}"})
        ax.set_xticks(range(len(data[net])))
        ax.set_xticklabels(["total" if x["is_total"] else art.label(x["layer"], "cycle_model.csv:layer")
                            for x in data[net]], rotation=35, ha="right", rotation_mode="anchor")
        ax.set_title(NET_TITLE.get(net, net), loc="left", fontsize=FS, weight="bold", pad=2)
        ax.set_ylim(0, 100)
        ax.yaxis.grid(True, color="0.88", lw=0.4, zorder=0)
    axs[0].set_ylabel("%")
    handles = [Patch(lw=0.5, label="MAC-active cycles (model)", **ST_MODEL),
               Patch(lw=0.5, label="PE utilization (model)", facecolor="0.8", edgecolor="black", hatch="\\\\\\\\"),
               Patch(lw=0.5, label=c.hw_name, **ST_HW) if any_hw else
               Patch(lw=0.5, label="KV260: board data pending", fill=False,
                     **{k: v for k, v in ST_PH.items() if k != "facecolor"})]
    fig.legend(handles=handles, ncol=2, loc="outside lower center", handlelength=1.4,
               columnspacing=0.8)
    return c.save(art, fig, rows)


# --------------------------------------------------------------------------------------------
# B2: latency vs clock
# --------------------------------------------------------------------------------------------
def fig_b2(c: FCtx) -> Artifact:
    """B2 clock sweep: (a) PL latency, (b) SOM-rail dP (INA260), (c) energy/image; x = pl_clk0."""
    art = c.art("fig_b2_clock")
    vs = impl_variants(art)
    data = {net: a3_net(art, net) for net in NETS}
    hwr = [r for r in (art.rows("hw_b2_clock.csv", hw=True) or []) if not r.get("skipped_reason")
           and r.get("latency_us")]
    ents = [e for e in power_summaries(art, "hw_b2_power_ina260") if e["clock"]]
    fig, axs = plt.subplots(1, 3, figsize=(COL_W, 1.95), sharex=True, layout="constrained")
    rows = []
    mk = {"lenet5": "o", "cifar10": "s"}
    ls = {"lenet5": "-", "cifar10": "--"}
    ax = axs[0]
    for net in NETS:
        d = data[net]
        if d and d[-1]["is_total"] and d[-1]["rtl"] is not None and vs:
            tot = d[-1]["rtl"]
            pts = [(fnum(r["pl_clk0_mhz_actual"]), div(tot, at(r, "pl_clk0_mhz_actual"), "cycles/MHz")) for r in vs]
            ax.plot([p[0] for p in pts], [p[1].value for p in pts], marker=mk[net], ls="none", mfc="white",
                    mec="0.35", ms=4, mew=0.7, zorder=4, label=f"{NET_TITLE[net]} RTL-sim cycles / post-impl f")
            rows += [{"panel": "latency", "net": net, "clock_mhz": f, "value": v.value, "unit": "us",
                      "kind": "rtl_sim_cycles/post_impl_clock", "src": v.origin} for f, v in pts]
        hn = sorted([r for r in hwr if r["net"] == net], key=lambda r: fnum(r["clock_readback_mhz"]))
        if hn:
            ax.plot([fnum(r["clock_readback_mhz"]) for r in hn], [fnum(r["latency_us"]) for r in hn],
                    marker=mk[net], ls=ls[net], color="black", ms=3.2, lw=0.8, zorder=3,
                    label=f"{NET_TITLE[net]} {c.hw_name}")
            rows += [{"panel": "latency", "net": net, "clock_mhz": fnum(r["clock_readback_mhz"]),
                      "value": fnum(r["latency_us"]), "unit": "us", "kind": "hw", "src": f"{r['_file']}:{r['_line']}"}
                     for r in hn]
    if not hwr:
        art.placeholder("B2 latency: hw_b2_clock.csv (source=hw)")
    ax.set_ylim(bottom=0)
    ax.set_title("PL latency (µs)", fontsize=FS - 1, pad=3)
    for ax, col, title, unit in ((axs[1], "accel_dp_w", "ΔP SOM rail (W)", "W"),
                                 (axs[2], "accel_energy_per_image_mj", "energy/image (mJ)", "mJ")):
        any_pt = False
        for net in NETS:
            en = sorted([e for e in ents if e["net"] == net and e["mean"].get(col)], key=lambda e: fnum(e["clock"]))
            if not en:
                continue
            any_pt = True
            xs = [fnum(e["clock"]) for e in en]
            ys = [fnum(e["mean"][col]) for e in en]
            es = [fnum(e["std"][col]) if e["std"] is not None and e["std"].get(col) else 0.0 for e in en]
            ax.errorbar(xs, ys, yerr=es, marker=mk[net], ls=ls[net], color="black", ms=3.2, lw=0.8, capsize=1.5,
                        elinewidth=0.6, zorder=3, label=f"{NET_TITLE[net]} {c.hw_name}")
            rows += [{"panel": col, "net": net, "clock_mhz": x, "value": y, "unit": unit, "kind": "hw INA260 mean",
                      "std": s, "src": f"{e['mean']['_file']}:{e['mean']['_line']}"} for x, y, s, e in zip(xs, ys, es, en)]
        if not any_pt:
            art.placeholder(f"B2 {col}: hw_b2_power_ina260_summary*.csv (source=hw)")
            ax.add_patch(Rectangle((0, 0), 1, 1, transform=ax.transAxes, fill=False, lw=0.5, edgecolor="0.55",
                                   hatch="////", linestyle=(0, (2, 1.5))))
            ax.text(0.5, 0.5, "board data\npending", transform=ax.transAxes, ha="center", va="center",
                    fontsize=FS - 1.5, style="italic", color="0.2",
                    bbox=dict(boxstyle="round,pad=0.2", fc="white", ec="0.55", lw=0.5, ls="--"))
            ax.set_yticks([])
        else:
            ax.set_ylim(bottom=0)
        ax.set_title(title, fontsize=FS - 1, pad=3)
    for ax in axs:
        ax.yaxis.grid(True, color="0.88", lw=0.4, zorder=0)
        ax.tick_params(labelsize=FS - 2)
    if not hwr:
        axs[0].text(0.5, 0.97, "board pending", transform=axs[0].transAxes, ha="center", va="top",
                    fontsize=FS - 2, style="italic", color="0.3")
    axs[1].set_xlabel("pl_clk0 (MHz)", fontsize=FS - 1)
    h, l = axs[0].get_legend_handles_labels()
    h2, l2 = axs[2].get_legend_handles_labels()
    seen = dict(zip(l + l2, h + h2))
    if seen:
        fig.legend(list(seen.values()), list(seen.keys()), loc="outside lower center", ncol=2, fontsize=FS - 2,
                   handletextpad=0.3, columnspacing=0.8)
    fig.suptitle(f"\u0394P and energy/image: {INA_LABEL}", fontsize=FS - 1.5, color="0.25")
    return c.save(art, fig, rows)


# --------------------------------------------------------------------------------------------
# B3: end-to-end breakdown (stacked horizontal bars)
# --------------------------------------------------------------------------------------------
B3_STACK = ["input_write", "status_clear", "start_done", "logit_read", "ps_dequant"]
B3_STYLE = {"input_write": dict(facecolor="white", hatch=""), "status_clear": dict(facecolor="0.85", hatch=""),
            "start_done": dict(facecolor="0.45", hatch=""), "logit_read": dict(facecolor="white", hatch="xxxx"),
            "ps_dequant": dict(facecolor="0.85", hatch="////")}


B3_FILES = {"safe": "hw_b3_breakdown.csv", "fast": "hw_b3_breakdown_fast.csv"}


def fig_b3(c: FCtx) -> Artifact:
    """B3 stacked host phases per net and host path (safe = per-word MMIO, fast = mapped numpy
    windows), median per phase; black tick = PL compute (cycle counter)."""
    art = c.art("fig_b3_breakdown")
    b = {}
    for hp, name in B3_FILES.items():
        rows = art.rows(name, hw=True) or []
        for k, r in latest(rows, lambda r: (r["net"], r["phase"])).items():
            b[(hp,) + k] = r
    keys = [(net, hp) for net in NETS for hp in B3_FILES]
    fig, ax = plt.subplots(figsize=(COL_W, 2.3), layout="constrained")
    out = []
    ys = list(range(len(keys)))
    have = False
    for y, (net, hp) in zip(ys, keys):
        left = 0.0
        if all((hp, net, p) in b for p in B3_STACK):
            have = True
            for p in B3_STACK:
                r = b[(hp, net, p)]
                v = fnum(r["median_us"])
                ax.barh(y, v, 0.55, left=left, edgecolor="black", lw=0.5, zorder=3, **B3_STYLE[p])
                out.append({"net": net, "host_path": hp, "phase": p, "median_us": v,
                            "src": f"{r['_file']}:{r['_line']}"})
                left += v
            if (hp, net, "pl_compute") in b:
                r = b[(hp, net, "pl_compute")]
                pc = fnum(r["median_us"])
                ax.plot([pc, pc], [y - 0.36, y + 0.36], color="black", lw=1.0, zorder=5)
                out.append({"net": net, "host_path": hp, "phase": "pl_compute", "median_us": pc,
                            "src": f"{r['_file']}:{r['_line']}"})
        else:
            art.placeholder(f"B3 {net} {hp}: {B3_FILES[hp]} (source=hw)")
            ax.add_patch(Rectangle((0, y - 0.275), 1, 0.55, transform=blended_transform_factory(ax.transAxes, ax.transData),
                                   fill=False, lw=0.5, edgecolor="0.55", hatch="////", linestyle=(0, (2, 1.5))))
    ax.set_yticks(ys)
    ax.set_yticklabels([f"{NET_TITLE[n]} {hp}" for n, hp in keys])
    ax.set_ylim(len(keys) - 0.5, -0.5)
    ax.set_xlabel("time per image (µs, median)")
    ax.xaxis.grid(True, color="0.88", lw=0.4, zorder=0)
    if have:
        handles = [Patch(edgecolor="black", lw=0.5, label=p.replace("_", " "), **B3_STYLE[p]) for p in B3_STACK]
        handles.append(plt.Line2D([], [], color="black", lw=1.0, label="PL compute (counter)"))
        fig.legend(handles=handles, ncol=3, loc="outside lower center", fontsize=FS - 1.5)
    else:
        ax.set_xticks([])
        _pending_label(ax)
    return c.save(art, fig, out)


def ALL(c: FCtx):
    style()
    return [fig_a3(c, wide=False), fig_a3(c, wide=True), fig_a4(c), fig_b2(c), fig_b3(c)]
